default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
 adapter: postgresql
 encoding: unicode
 database: marabit_development
 pool: 5
 host: localhost

test:
  <<: *default
  database: db/test

production:
  <<: *default
  database: db/production
