default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
 adapter: postgresql
 encoding: unicode
 database: marabit_development
 host: localhost
 timeout: 5000
 pool: 5


test:
  <<: *default
  database: db/test

production:
  <<: *default
  database: db/production
