# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05e080a58494793384d67dde2122fcb696bf163544c430cd977baf6ad922dbbac0a913ce604bd6f857f3464c5da3531ec42d9addc6ef862c6f38f4c094ec0aa7

test:
  secret_key_base: 9f403e6fc80d0fd7f0d07a3132f197e5039342c24e4222ace8641430c0d4166dab993f5da2591f83107cf2ade8b38040125eeabd2a9e7c689cdf015df9ab181c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
